In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
from matpowercaseframes import CaseFrames

In [ ]:
CASE_NAME = "../data/case9_reduced.m"
cf = CaseFrames(CASE_NAME)
cf.infer_numpy()
display(cf.branch)
display(cf.bus)
display(cf.gen)

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
branch,,,,,,,,,,,,,
1,4,5,0.0170,0.0920,0.158,250,250,250,0,0,1,-360,360
2,5,6,0.0390,0.1700,0.358,150,150,150,0,0,1,-360,360
3,6,7,0.0119,0.1008,0.209,150,150,150,0,0,1,-360,360
4,7,8,0.0085,0.0720,0.149,250,250,250,0,0,1,-360,360
5,8,9,0.0320,0.1610,0.306,250,250,250,0,0,1,-360,360
6,9,4,0.0100,0.0850,0.176,250,250,250,0,0,1,-360,360

,BUS_I,BUS_TYPE,PD,QD,GS,BS,BUS_AREA,VM,VA,BASE_KV,ZONE,VMAX,VMIN
bus,,,,,,,,,,,,,
4,4,3,0,0,0,0,1,1.040000,-2.216788,345,1,1.1,0.9
5,5,1,90,30,0,0,1,1.019544,-3.599309,345,1,1.1,0.9
6,6,2,0,0,0,0,1,1.025000,2.208471,345,1,1.1,0.9
7,7,1,100,35,0,0,1,1.012276,0.912347,345,1,1.1,0.9
8,8,2,0,0,0,0,1,1.025000,3.885641,345,1,1.1,0.9
9,9,1,125,50,0,0,1,1.005122,-3.900271,345,1,1.1,0.9

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN
gen,,,,,,,,,,
1,4,71.730424,38.076988,300,-300,1.040,100,1,250,10
2,8,163.000000,-11.552844,300,-300,1.025,100,1,300,10
3,6,85.000000,-26.910102,300,-300,1.025,100,1,270,10

In [ ]:
# cf.to_excel("../data/case9_reduced.xlsx")